name: 'Seiten Deploy'
description: 'Sends an archive (tar.gz) to your Seiten instance'
inputs:
  url:
    description: 'The URL of your Seiten instance'
    required: true
  gpg-key:
    description: 'The GPG key to use for signing'
    required: true
  archive:
    description: 'The path to the archive to send'
    required: true
  path:
    description: 'The path to extract the archive to'
runs:
  using: "composite"
  steps:
    - name: Import GPG key
      shell: bash
      run: |
        echo "${{ inputs.gpg-key }}" | gpg --import

    - name: Signature
      shell: bash
      run: |
        gpg --detach-sign --armor -o signature.asc "${{ inputs.archive }}"

    - name: Upload
      shell: bash
      run: |
        curl -v \
        -F "archive=@${{ inputs.archive }}" \
        -F "signature=@signature.asc" \
        ${{ inputs.url }}/upload/${{ inputs.path }}
